delete from autoria;
delete from autor;
delete from livro;

insert into Livro (Titulo,Editora,Edicao) values ('As Cruzadas Vistas Pelos Árabes','Difel',  7 );
insert into Livro (Titulo,Editora,Edicao) values ('O Buraco Na Parede','Campo das Letras',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('O Desejo De Kianda','Dom Quixote',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('O Rochedo De Tanios','Difel',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('E Se Tivesse A Bondade De Me Dizer Porquê ?','Edições Rolim',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('Os Prisioneiros','Companhia das Letras',  4 );
insert into Livro (Titulo,Editora,Edicao) values ('Yaka','Dom Quixote',  2 );
insert into Livro (Titulo,Editora,Edicao) values ('Cavalos Em Fuga','Editorial Presença',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('A Coleira Do Cão','Companhia das Letras',  4 );
insert into Livro (Titulo,Editora,Edicao) values ('Samarcanda','Difel',  4 );
insert into Livro (Titulo,Editora,Edicao) values ('Morte Em Pleno Verão','Relógio Dágua', null);
insert into Livro (Titulo,Editora,Edicao) values ('A Jangada De Pedra','Caminho',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('Agosto','Dom Quixote',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('Sede De Amar','Editorial Presença',  2 );
insert into Livro (Titulo,Editora,Edicao) values ('Escalas Do Levante','Difel',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('Deste Mundo E Do Outro','Arcádia', null);
insert into Livro (Titulo,Editora,Edicao) values ('Lúcia McCartney','Companhia das Letras',  6 );
insert into Livro (Titulo,Editora,Edicao) values ('Os Meteoros','Dom Quixote',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('Lituma Nos Andes','Dom Quixote',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('Leão, O Africano','Bertrand',  4 );
insert into Livro (Titulo,Editora,Edicao) values ('A Geração Da Utopia','Dom Quixote',  2 );
insert into Livro (Titulo,Editora,Edicao) values ('História Do Cerco De Lisboa','Caminho',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('O Selvagem Da Ópera','Companhia das Letras',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('Horas Más','Queztal',  3 );
insert into Livro (Titulo,Editora,Edicao) values ('Os Jardins De Luz','Difel',  3 );
insert into Livro (Titulo,Editora,Edicao) values ('Romance Negro E Outras Histórias','Campo das Letras',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('Uma Ceia De Amor','Dom Quixote',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('O Caso Morel','Bertrand',  null );
insert into Livro (Titulo,Editora,Edicao) values ('Ensaio Sobre A Cegueira','Caminho',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('O Século Primeiro Depois De Beatriz','Difel',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('Feliz Ano Novo','Contexto',  null );
insert into Livro (Titulo,Editora,Edicao) values ('Gaspar, Belchior & Baltasar','Dom Quixote',  3 );
insert into Livro (Titulo,Editora,Edicao) values ('Um Deus Passeando Pela Brisa Da Tarde','Caminho',  4 );
insert into Livro (Titulo,Editora,Edicao) values ('Parábola Do Cágado Velho','Dom Quixote',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('Giles & Jeanne','Dom Quixote',  20 );
insert into Livro (Titulo,Editora,Edicao) values ('O Cobrador','Companhia das Letras',  3 );
insert into Livro (Titulo,Editora,Edicao) values ('Adeus Princesa','Dom Quixote', null );
insert into Livro (Titulo,Editora,Edicao) values ('A Grande Arte','Edições 70',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('A Casa Verde','Livros do Brasil',  null);
insert into Livro (Titulo,Editora,Edicao) values ('Bufo & Spallanzani','Companhia das Letras',  24 );
insert into Livro (Titulo,Editora,Edicao) values ('Lueji','Dom Quixote',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('Vastas Emoções E Pensamentos Imperfeitos','Dom Quixote',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('Conversa Na Catedral','Circulo de Leitores',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('Agrião','Relógio Dágua',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('Como Peixe Na Água','Dom Quixote',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('A Cidade E Os Cães','Europa América', null);
insert into Livro (Titulo,Editora,Edicao) values ('A Paixão Do Conde De Fróis','Edições Rolim',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('Olhos E Cão Azul','Queztal', null);
insert into Livro (Titulo,Editora,Edicao) values ('Domingo De Ramos','Circulo de Leitores',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('A Inaudita Guerra Da Avenida Gago Coutinho','Caminho',  3 );
insert into Livro (Titulo,Editora,Edicao) values ('A Guerra Do Fim Do Mundo','Bertrand',  null);
insert into Livro (Titulo,Editora,Edicao) values ('A incrível e Triste História Da Cândida Eréndira e Da Sua Avó Desalmada','Europa América',  2 );
insert into Livro (Titulo,Editora,Edicao) values ('Um Esquema','Edições Rolim',  2 );
insert into Livro (Titulo,Editora,Edicao) values ('Casos Do Beco Das Sardinheiras','Caminho',  2 );
insert into Livro (Titulo,Editora,Edicao) values ('Quem Matou Palomito Molero ?','Dom Quixote',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('O General No Seu Labirinto','Dom Quixote',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('Ponto Pé De Flor','Dom Quixote',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('História De Mayta','Dom Quixote',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('O Falador','Dom Quixote',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('A Revoada','Queztal',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('Do Amor E Outros Demónios','Dom Quixote',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('Pantaleão E As Visitadoras','Europa América',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('O Outono Do Patriarca','Europa América',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('Os Cachoros Os Chefes','Bertrand',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('Cem Anos De Solidão','Europa América',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('A Tia Julia E O Escrevedor','Dom Quixote',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('Elogio Da Madrasta','Dom Quixote',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('As Aventuras De Miguel Littín Clandestino No Chile','O Jornal',  1 );
insert into Livro (Titulo,Editora,Edicao) values ('Ninguém Escreve Ao Coronel','Europa América',  1 );

insert into Autor (Nome, Nacionalidade) values ('Mário de Carvalho','Português');
insert into Autor (Nome, Nacionalidade) values ('Clara Pinto Corrêia','Português');
insert into Autor (Nome, Nacionalidade) values ('Ruben Fonseca','Brasileiro');
insert into Autor (Nome, Nacionalidade) values ('Mario Vargas Llosa','Peruano');
insert into Autor (Nome, Nacionalidade) values ('Amin Maalouf','Libanês');
insert into Autor (Nome, Nacionalidade) values ('Gabriel Garcia Marques','Colombiano');
insert into Autor (Nome, Nacionalidade) values ('Yukio Mishima','Japonês');
insert into Autor (Nome, Nacionalidade) values ('Pablo Nerruda','Chileno');
insert into Autor (Nome, Nacionalidade) values (9,'Angolano');
insert into Autor (Nome, Nacionalidade) values ('José Saramago','Português');
insert into Autor (Nome, Nacionalidade) values ('Michael Tournier','Françês');

insert into Autoria (IDAutor,IDLivro) values (1,5);
insert into Autoria (IDAutor,IDLivro) values (1,33);
insert into Autoria (IDAutor,IDLivro) values (1,47);
insert into Autoria (IDAutor,IDLivro) values (1,50);
insert into Autoria (IDAutor,IDLivro) values (1,54);
insert into Autoria (IDAutor,IDLivro) values (2,5);
insert into Autoria (IDAutor,IDLivro) values (2,37);
insert into Autoria (IDAutor,IDLivro) values (2,44);
insert into Autoria (IDAutor,IDLivro) values (2,49);
insert into Autoria (IDAutor,IDLivro) values (2,53);
insert into Autoria (IDAutor,IDLivro) values (2,57);
insert into Autoria (IDAutor,IDLivro) values (3,2);
insert into Autoria (IDAutor,IDLivro) values (3,6);
insert into Autoria (IDAutor,IDLivro) values (3,9);
insert into Autoria (IDAutor,IDLivro) values (3,13);
insert into Autoria (IDAutor,IDLivro) values (3,17);
insert into Autoria (IDAutor,IDLivro) values (3,23);
insert into Autoria (IDAutor,IDLivro) values (3,26);
insert into Autoria (IDAutor,IDLivro) values (3,28);
insert into Autoria (IDAutor,IDLivro) values (3,31);
insert into Autoria (IDAutor,IDLivro) values (3,36);
insert into Autoria (IDAutor,IDLivro) values (3,38);
insert into Autoria (IDAutor,IDLivro) values (3,40);
insert into Autoria (IDAutor,IDLivro) values (3,42);
insert into Autoria (IDAutor,IDLivro) values (4,19);
insert into Autoria (IDAutor,IDLivro) values (4,39);
insert into Autoria (IDAutor,IDLivro) values (4,43);
insert into Autoria (IDAutor,IDLivro) values (4,45);
insert into Autoria (IDAutor,IDLivro) values (4,46);
insert into Autoria (IDAutor,IDLivro) values (4,51);
insert into Autoria (IDAutor,IDLivro) values (4,55);
insert into Autoria (IDAutor,IDLivro) values (4,58);
insert into Autoria (IDAutor,IDLivro) values (4,59);
insert into Autoria (IDAutor,IDLivro) values (4,62);
insert into Autoria (IDAutor,IDLivro) values (4,64);
insert into Autoria (IDAutor,IDLivro) values (4,66);
insert into Autoria (IDAutor,IDLivro) values (4,67);
insert into Autoria (IDAutor,IDLivro) values (5,1);
insert into Autoria (IDAutor,IDLivro) values (5,4);
insert into Autoria (IDAutor,IDLivro) values (5,10);
insert into Autoria (IDAutor,IDLivro) values (5,15);
insert into Autoria (IDAutor,IDLivro) values (5,20);
insert into Autoria (IDAutor,IDLivro) values (5,25);
insert into Autoria (IDAutor,IDLivro) values (5,30);
insert into Autoria (IDAutor,IDLivro) values (6,24);
insert into Autoria (IDAutor,IDLivro) values (6,48);
insert into Autoria (IDAutor,IDLivro) values (6,52);
insert into Autoria (IDAutor,IDLivro) values (6,56);
insert into Autoria (IDAutor,IDLivro) values (6,60);
insert into Autoria (IDAutor,IDLivro) values (6,61);
insert into Autoria (IDAutor,IDLivro) values (6,63);
insert into Autoria (IDAutor,IDLivro) values (6,65);
insert into Autoria (IDAutor,IDLivro) values (6,68);
insert into Autoria (IDAutor,IDLivro) values (6,69);
insert into Autoria (IDAutor,IDLivro) values (7,08);
insert into Autoria (IDAutor,IDLivro) values (7,11);
insert into Autoria (IDAutor,IDLivro) values (7,14);
insert into Autoria (IDAutor,IDLivro) values (9,3);
insert into Autoria (IDAutor,IDLivro) values (9,7);
insert into Autoria (IDAutor,IDLivro) values (9,21);
insert into Autoria (IDAutor,IDLivro) values (9,34);
insert into Autoria (IDAutor,IDLivro) values (9,41);
insert into Autoria (IDAutor,IDLivro) values (10,12);
insert into Autoria (IDAutor,IDLivro) values (10,16);
insert into Autoria (IDAutor,IDLivro) values (10,22);
insert into Autoria (IDAutor,IDLivro) values (10,29);
insert into Autoria (IDAutor,IDLivro) values (11,18);
insert into Autoria (IDAutor,IDLivro) values (11,27);
insert into Autoria (IDAutor,IDLivro) values (11,32);
insert into Autoria (IDAutor,IDLivro) values (11,35);

